"""empty message

Revision ID: 622d91fed164
Revises: 09c9fe509a80
Create Date: 2024-06-08 15:57:58.385225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622d91fed164'
down_revision: Union[str, None] = '09c9fe509a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_message_sent', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('second_message_sent', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('third_message_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'third_message_sent')
    op.drop_column('users', 'second_message_sent')
    op.drop_column('users', 'first_message_sent')
    # ### end Alembic commands ###
