"""empty message

Revision ID: 8b13af56fb08
Revises: 622d91fed164
Create Date: 2024-06-09 15:35:12.397524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b13af56fb08'
down_revision: Union[str, None] = '622d91fed164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_message', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('second_message', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('third_message', sa.DateTime(), nullable=True))
    op.drop_column('users', 'first_message_sent')
    op.drop_column('users', 'third_message_sent')
    op.drop_column('users', 'second_message_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_message_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('third_message_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_message_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'third_message')
    op.drop_column('users', 'second_message')
    op.drop_column('users', 'first_message')
    # ### end Alembic commands ###
